name: digital_theme
display_name: Digital Center Theme for Prestashop 1.7
version: 1.0.0
author:
  name: "Elías Rafael Rodelo"
  email: "cto@digitalcenter.com.co"
  url: "https://www.digitalcenter.com.co"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-left-side-column:
      name: Two Columns, small left column
      description: Two columns with a small left column

global_settings:
  configuration:
    PS_QUICK_VIEW: false
    PS_PNG_QUALITY: 8
  modules:
    to_enable:
      - wtcustomhtml
      - wtmegamenu
    to_disable:
      - ps_banner
  hooks:
    modules_to_hook:
      displayNav1:
        - ps_contactinfo
        - ps_languageselector
        - ps_currencyselector
      displayNav:
        - ps_searchbar
        - ps_customersignin
        - ps_shoppingcart
      displayMenu:
        - wtmegamenu
      displayTopHome:
        - ps_imageslider
        - wtcustomhtml
      displayCenterHome:
        - blockreassurance
        - ps_featuredproducts
        - wtcustomhtml
      displayBottomHome:
        - wtcustomhtml
        - ps_customtext
        - dt_brands
      displayFooterBefore:
        - ps_emailsubscription
      displayFooter:
        - ps_customeraccountlinks
        - ps_linklist
      displayFooterRight:
        - ps_socialfollow
      displayBottomFooter:
        - wtcustomhtml
      displayFooterAfter:
        - ps_contactinfo
  image_types:
    cart_default:
      width: 80
      height: 80
      scope: [products]
    small_default:
      width: 125
      height: 125
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 300
      height: 300
      scope: [products, categories, manufacturers, suppliers]
    large_default:
      width: 500
      height: 500
      scope: [products]
    home_default:
      width: 250
      height: 250
      scope: [products]
    category_default:
      width: 960
      height: 350
      scope: [categories]

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-side-column
    best-sales: layout-left-side-column

dependencies:
  modules:
    - wtcustomhtml
    - productcomments
    - dt_brands
    - wtmegamenu
